### PR TITLE
Update check-windows.yaml

### PR DESCRIPTION
**Pull request by pachamaltese**

### CODE REVIEW

**Comment by pachamaltese** [comment]
@jonkeane this PR restores Windows testing, it works well with psql v10.0
the only change needed in this PR is to re-add `push` at the beginning of the Windows testing instructions

**Comment by pachamaltese** [comment]
acidentally, I closed the PR, it's running the tests again, but here is today's result
https://github.com/jonkeane/dittodb/actions/runs/137541081

**Comment by pachamaltese** [comment]
@jonkeane v11 works !!

**Comment by jonkeane** [comment]
Yup, I also noticed that `push` looked like it had been removed from when the action was run, so I added that back in. Thanks for digging into this!

**Pull request merged**
